name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files after checkout (verify repo files)
        run: |
          echo "Listing files after checkout..."
          ls -R  # Печатаем все файлы в репозитории после checkout

      - name: Build Docker image
        run: docker build -t vlad21165/my-k8s-app:latest -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Set up Minikube certificates
        run: |
          mkdir -p $HOME/.minikube/profiles/minikube
          echo "${{ secrets.CLIENT_CRT }}" | base64 -d > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.CLIENT_KEY }}" | base64 -d > $HOME/.minikube/profiles/minikube/client.key
          echo "${{ secrets.CA_CRT }}" | base64 -d > $HOME/.minikube/ca.crt

          # Исправление путей в kubeconfig
          sed -i "s|/home/vlad|$HOME|g" $HOME/.kube/config

          # Проверка сертификатов
          ls -l $HOME/.minikube/profiles/minikube
          ls -l $HOME/.minikube

      - name: Debug and List k8s directory content
        run: |
          echo "Checking content of the k8s directory..."
          ls -l ./k8s  # Проверяем содержимое папки k8s относительно текущей директории

      - name: Apply Kubernetes manifests
        run: |
          echo "Applying Kubernetes manifests..."
          export KUBECONFIG=$HOME/.kube/config
          ls -l ./k8s  # Повторно проверяем содержимое папки перед применением
          kubectl apply -f ./k8s/deployment.yaml  # Применяем манифесты
          kubectl apply -f ./k8s/service.yaml
