name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build -t vlad21165/my-k8s-app:latest -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Minikube certificates
        run: |
          mkdir -p $HOME/.minikube/profiles/minikube
          echo "${{ secrets.CLIENT_CRT }}" > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.CLIENT_KEY }}" > $HOME/.minikube/profiles/minikube/client.key
          echo "${{ secrets.CA_CRT }}" > $HOME/.minikube/ca.crt

          # Проверка файлов
          ls -l $HOME/.minikube/profiles/minikube
          ls -l $HOME/.minikube

      - name: Apply Kubernetes manifests
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Debug paths
        run: |
          echo "Listing .kube directory:"
          ls -l $HOME/.kube
          echo "Listing .minikube directory:"
          ls -l $HOME/.minikube
          echo "Listing .minikube/profiles/minikube:"
          ls -l $HOME/.minikube/profiles/minikube
