name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Запускать pipeline на изменения в ветке master

jobs:
  build:
    runs-on: ubuntu-latest  # Платформа для выполнения CI/CD

    steps:
      # Шаг для загрузки кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v2  

      # Шаг для установки Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      # Шаг для кэширования Docker слоев
      - name: Cache Docker layers
        uses: actions/cache@v2  
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Шаг для сборки Docker образа
      - name: Build Docker image
        run: docker build -t vlad21165/my-k8s-app:latest -f Dockerfile .  # Явно указываем путь к Dockerfile

      # Шаг для логина в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Токен для Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Пароль или токен Docker Hub

      # Шаг для публикации Docker образа на Docker Hub
      - name: Push Docker image
        run: docker push vlad21165/my-k8s-app:latest  # Публикуем образ в Docker Hub

      # Шаги для деплоя в Kubernetes (по необходимости)
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1  # Используем старую версию azure/setup-kubectl

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
