name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t vlad21165/my-k8s-app:latest -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Set up Minikube certificates
        run: |
          mkdir -p $HOME/.minikube/profiles/minikube
          echo "${{ secrets.CLIENT_CRT }}" | base64 -d > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.CLIENT_KEY }}" | base64 -d > $HOME/.minikube/profiles/minikube/client.key
          echo "${{ secrets.CA_CRT }}" | base64 -d > $HOME/.minikube/ca.crt

          # Исправление путей в kubeconfig
          sed -i "s|/home/vlad|$HOME|g" $HOME/.kube/config

          # Проверка сертификатов
          ls -l $HOME/.minikube/profiles/minikube
          ls -l $HOME/.minikube

      - name: List current directory and files in k8s directory
        run: |
          echo "Current directory:"
          pwd
          echo "Listing all files recursively:"
          ls -R
          
      - name: Debug Kubernetes manifests path
        run: |
          echo "Checking if files exist at the expected path:"
          ls -l /home/runner/work/my-k8s-app/my-k8s-app/k8s
          
      - name: Apply Kubernetes manifests
        run: |
          echo "Applying Kubernetes manifests..."
          export KUBECONFIG=$HOME/.kube/config
          ls -l /home/runner/work/my-k8s-app/my-k8s-app/k8s  # Проверка, существуют ли файлы перед применением
          kubectl apply -f /home/runner/work/my-k8s-app/my-k8s-app/k8s/deployment.yaml  # Используем полный путь
          kubectl apply -f /home/runner/work/my-k8s-app/my-k8s-app/k8s/service.yaml    # Используем полный путь
